version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
    volumes:
      - .:/app
      - /app/node_modules
      - ./database.db:/app/database.db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
